version: "3"
services:
  python3:
    build:
      dockerfile: Dockerfile
    container_name: "python3"
    init : true
    tty: true
    privileged: true
    volumes:
      - ${HOME}/git:/home/${PYUSER}/git
      - ${PYTHON_VOLUME_HOME}/kafka:/home/${PYUSER}/kafka
      - ${PYTHON_VOLUME_HOME}/spark:/home/${PYUSER}/spark
      - ${PYTHON_VOLUME_HOME}/python_packages/polo-sdk-python:/home/polo_sdk
    networks:
      shared-network:
        ipv4_address: 172.29.0.9
    ports:
      - '21022:22'
    deploy:
      resources:
        limits:
          cpus: '1.0'

networks:
  shared-network:
    external: true
